version: 2
jobs:
  build:
    working_directory: ~/pulibrary/pul_metadata_services

    docker:
      - image: circleci/ruby:2.4.2-node-browsers
        environment:
          RAILS_ENV: test

    steps:
      - checkout

      - restore_cache:
          keys:
          - pul_metadata_services-{{ checksum "Gemfile" }}
          - pul_metadata_services-

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle

      - save_cache:
          key: pul_metadata_services-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle

      - run:
          name: Rspec
          command: bundle exec rspec spec
          environment:
            RAILS_ENV: test
